name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare SSH
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
      shell: bash
      env:
        SERVER_IP: ${{ secrets.HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        scp -r . user@$SERVER_IP:$APP_PATH
        ssh user@$SERVER_IP << 'EOF'
          cd $APP_PATH
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart $YOUR_APP
        EOF
      shell: bash
      env:
        SERVER_IP: ${{ secrets.HOST }}
        APP_PATH: ${{ secrets.PATH }}
        YOUR_APP: ${{ secrets.APP }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
