name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        source /home/azureuser/venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to server
      run: |
        source /home/azureuser/venv/bin/activate
        sudo systemctl restart ${{ secrets.APP }}
      env:
        APP: ${{ secrets.APP }}
